### PR TITLE
add tidydann to model spec search

### PR DESCRIPTION
**Pull request by simonpcouch**
This PR adds [tidydann](https://github.com/tidymodels/parsnip/issues/996) to the model search page by re-running the parsnip model code in `make_function_lists.R`.

In the meantime, another package also contributed new model specifications:

```
anti_join(parsnip_models, parsnip_models_old) %>% select(title, engine, package)
#> # A tibble: 7 × 3
#>   title                                                          engine                package 
#>   <chr>                                                          <chr>                 <fct>   
#> 1 K-nearest neighbors                                            <code>cuda.ml</code>  parsnip 
#> 2 Random forest                                                  <code>cuda.ml</code>  parsnip 
#> 3 Linear support vector machines                                 <code>cuda.ml</code>  parsnip 
#> 4 Polynomial support vector machines                             <code>cuda.ml</code>  parsnip 
#> 5 Radial basis function support vector machines                  <code>cuda.ml</code>  parsnip 
#> 6 Discriminant Adaptive Nearest Neighbor Classification          <code>dann</code>     tidydann
#> 7 Discriminant Adaptive Nearest Neighbor With Subspace Reduction <code>sub_dann</code> tidydann
```

Although parsnip is able to correctly hook into cuda.ml's model registration, the package [doesn't seem to have a pkgdown website](https://github.com/mlverse/cuda.ml), so the search page would refer people to parsnip's main model docs, which don't have information on cuda.ml. I'd make the case that we ought to add cuda.ml to `excl` in `parsnip_pkgs <- parsnip_pkgs[!(parsnip_pkgs %in% excl)]` but wanted to surface that here before doing so!

[EDITs: accidentally submitted issue early, finished typing description]

### CODE REVIEW

**Comment by EmilHvitfeldt** [comment]
Great! let us send it in, after https://github.com/tidymodels/tidymodels.org/pull/40 is merged

**Comment by simonpcouch** [comment]
Awesome! Any opinions on the addition/exclusion of the cuda.ml specs?

**Comment by EmilHvitfeldt** [comment]
Yes, we should  add cuda.ml to `excl` as you suggested

**Comment by topepo** [comment]
Let's hold off on this for a bit. The current plan is to make a new [parsnip model](https://github.com/gmcmacran/tidydann/issues/7#issuecomment-1740142229)

**Comment by gmcmacran** [comment]
Hey everyone, 

I recently closed https://github.com/gmcmacran/tidydann/issues/7. I believe tidydann is ready for the addition to the model search page. I am holding off releasing the updates to CRAN until I get sign off here. Let me know how yall would like to proceed.

**Comment by EmilHvitfeldt** [comment]
Hello @gmcmacran! the search right now only works with models from packages on CRAN. If @topepo is happy with the changes, then you can send it to CRAN and I'll make it so it appears in the model search :)

**Comment by gmcmacran** [comment]
The changes have been uploaded to cran. Let me know if I need to do anything else.

https://cran.r-project.org/package=tidydann

**Comment by EmilHvitfeldt** [comment]
thank you! that is all we need, I'll get to this next week

**Pull request merged**
